language: rust
os:
  - linux
  - osx
  - windows
cache: cargo
rust:
  - stable
  - beta
  - nightly
  - 1.31.1
  - 1.31.0
# before_deploy: "cargo build --release --verbose"
# deploy:
#   skip_cleanup: true
#   provider: releases
#   api_key: $GH_TOKEN
#   file: target/release/gi
#   draft: true
#   on:
#     tags: true
